export declare enum Role {
  CHIL = "CHIL",
  CLERGY = "CLERGY",
  FATH = "FATH",
  FRIEND = "FRIEND",
  GODP = "GODP",
  HUSB = "HUSB",
  MOTH = "MOTH",
  MULTIPLE = "MULTIPLE",
  NGHBR = "NGHBR",
  OFFICIATOR = "OFFICIATOR",
  PARENT = "PARENT",
  WIFE = "WIFE",
  WITN = "WITN",
  OTHER = "OTHER",
}
